# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fe584f28fb79911876f05a5d9441fbdbac79b6e0516d183e877c407be51c684301ab672999abec95d86348c9a016aa91ba44712f2657312065d442d44bfba43

test:
  secret_key_base: 74d47f91a726340acf8344d95abd12766c45dc90b83cd144adab2a13e11120baf645c450b69951c56e49733927ed513c1ea85f968d9581af1684fa392ffd205a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
